<a href="https://colab.research.google.com/github/khawajaacode/NeuronCraft/blob/main/00_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import tensorflow as tf
print(tf.__version__)





2.17.0


In [25]:
scalar = tf.constant(8)

scalar, scalar.ndim, tf.size, tf.shape, tf.rank

(<tf.Tensor: shape=(), dtype=int32, numpy=8>,
 0,
 <function tensorflow.python.ops.array_ops.size_v2(input, out_type=None, name=None)>,
 <function tensorflow.python.ops.array_ops.shape_v2(input, out_type=None, name=None)>,
 <function tensorflow.python.ops.array_ops.rank(input, name=None)>)

In [29]:
vector = tf.constant([29,3])
vector, vector.ndim, vector.shape

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([29,  3], dtype=int32)>,
 1,
 TensorShape([2]))

In [27]:
matrix = tf.constant([[10,7],
                      [9,1],
                      [32, 8]])
matrix, matrix.ndim, tf.size(matrix), tf.shape(matrix)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 9,  1],
        [32,  8]], dtype=int32)>,
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>)

In [30]:
tensor =   tf.constant([[32,33,23],
                        [10,7,3]])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[32, 33, 23],
       [10,  7,  3]], dtype=int32)>

In [31]:
rank_1_tensor = tensor
print(rank_1_tensor)

tf.Tensor(
[[32 33 23]
 [10  7  3]], shape=(2, 3), dtype=int32)


In [32]:
tf.shape(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [33]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [34]:
tensor


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[32, 33, 23],
       [10,  7,  3]], dtype=int32)>

In [38]:
tensor_1 = tf.random.Generator.from_seed(42)
tensor_1 = tensor_1.normal(shape=(5,300))
tensor_2 = tf.random.Generator.from_seed(40)
tensor_2 = tensor_2.normal(shape=(5,300))

tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345, -0.48535708, ..., -1.655111  ,
          0.20270453, -0.05907417],
        [-0.08876546, -0.2818856 , -1.2894468 , ..., -0.36720887,
         -0.40844494, -0.9370698 ],
        [-0.75371194, -1.7472465 , -0.26269418, ..., -2.465845  ,
         -1.1038724 ,  0.5590708 ],
        [-0.9807223 , -0.16120234,  1.0154027 , ...,  0.3698049 