<a href="https://colab.research.google.com/github/khawajaacode/NeuronCraft/blob/main/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## In This Notebook, we are going to cover some of the most fundamental concepts of Tensors using Tensorflow.


# In This Notebook, we are going to cover some of the most fundamental concepts of Tensors using Tensorflow.
  

More Specifically, we are going to cover:
* Introduction to tensors
* Getting info from Tensors
* Manipulating Tensors
* Tensors and Numpy
* Using @tf.function
* Using GPUs with Tensorflow
* Exercises to Try for Yourself!

## Introduction to Tensors

In [2]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
# Create Tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [6]:
# Create Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [12]:
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [14]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

What we've created so far:

* Scalar a single number
* Vector a number with Direction
* Matrix a 2-dimensional array of Numbers
* Tensors: an n-dimensional array of Number( when n can be any num, a 0-dim tensor is a scalar, a 1-dim tensor is vector)