<a href="https://colab.research.google.com/github/khawajaacode/NeuronCraft/blob/main/First_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import tensorflow as tf

tf.__version__

'2.17.0'

In [63]:
200 * 80 / 100

160.0

In [64]:
X = tf.range(0, 200, 10)
y = tf.range(10, 210, 10)

X_train = X[:16]
y_train = y[:16]

X_test = X[16:]
y_test = y[16:]

X_train, y_train, X_test, y_test

(<tf.Tensor: shape=(16,), dtype=int32, numpy=
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
        130, 140, 150], dtype=int32)>,
 <tf.Tensor: shape=(16,), dtype=int32, numpy=
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([160, 170, 180, 190], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([170, 180, 190, 200], dtype=int32)>)

In [65]:
model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation = "relu", input_shape = [1]),
    tf.keras.layers.Dense(10, activation = "relu", input_shape = [1]),
    tf.keras.layers.Dense(1 , input_shape = [1])

])

model_1.compile(loss = tf.keras.losses.mae,
                optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),
                metrics = ["mae"])

model_1.fit(X_train, y_train, epochs = 150)

Epoch 1/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 81.3283 - mae: 81.3283
Epoch 2/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 70.3620 - mae: 70.3620
Epoch 3/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 59.3288 - mae: 59.3288
Epoch 4/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 49.7738 - mae: 49.7738
Epoch 5/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 40.2885 - mae: 40.2885
Epoch 6/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 30.1736 - mae: 30.1736
Epoch 7/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 19.3454 - mae: 19.3454
Epoch 8/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7.7025 - mae: 7.7025
Epoch 9/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 8.3716 - mae: 8.3716
Epoch 10/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 15.6715 - mae: 15.6715
Epoch 11/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 19.8376 - mae: 19.8376
Epoch 12/150
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 20.8728 - mae: 20.8728
Epoch 13/150
1/1 ━━━━━━━━━━━━━━

In [66]:
model_1.predict(X_test), y_test

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


(array([[171.7424 ],
        [181.97644],
        [192.21048],
        [202.4445 ]], dtype=float32),
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([170, 180, 190, 200], dtype=int32)>)